version: '3.8'
services:
  stablequeue:
    image: stablequeue-app:latest
    build: .
    container_name: stablequeue
    ports:
      - "8083:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./models/Stable-diffusion:/app/models/Stable-diffusion
      - ./models/Lora:/app/models/Lora
      - ./outputs:/app/outputs
    environment:
      - PORT=3000
      - CONFIG_DATA_PATH=/usr/src/app/data
      - STABLE_DIFFUSION_SAVE_PATH=/app/outputs
      - LORA_PATH=/app/models/Lora
      - CHECKPOINT_PATH=/app/models/Stable-diffusion
      - NODE_ENV=development
    restart: unless-stopped
